Repository genome-nexus/genome-nexus, pull requests merged in 2023-07, with the labels that each got.

#687 Update oncokb java api client and mapper configs
  .github/workflows/oncokb_test.yml
  .gitignore
  pom.xml
  service/src/main/java/org/cbioportal/genome_nexus/service/transformer/ExternalResourceTransformer.java
Labels: bug, dependencies

#691 Fix failing my variant info tests
  model/src/main/java/org/cbioportal/genome_nexus/model/my_variant_info_model/AlleleCount.java
  model/src/main/java/org/cbioportal/genome_nexus/model/my_variant_info_model/AlleleFrequency.java
  model/src/main/java/org/cbioportal/genome_nexus/model/my_variant_info_model/AlleleNumber.java
  model/src/main/java/org/cbioportal/genome_nexus/model/my_variant_info_model/Alleles.java
  model/src/main/java/org/cbioportal/genome_nexus/model/my_variant_info_model/Ann.java
  model/src/main/java/org/cbioportal/genome_nexus/model/my_variant_info_model/ClinVar.java
  model/src/main/java/org/cbioportal/genome_nexus/model/my_variant_info_model/Cosmic.java
  model/src/main/java/org/cbioportal/genome_nexus/model/my_variant_info_model/Dbsnp.java
  model/src/main/java/org/cbioportal/genome_nexus/model/my_variant_info_model/Gene.java
  model/src/main/java/org/cbioportal/genome_nexus/model/my_variant_info_model/Gnomad.java
  model/src/main/java/org/cbioportal/genome_nexus/model/my_variant_info_model/Hg19.java
  model/src/main/java/org/cbioportal/genome_nexus/model/my_variant_info_model/Hg38.java
  model/src/main/java/org/cbioportal/genome_nexus/model/my_variant_info_model/Hgvs.java
  model/src/main/java/org/cbioportal/genome_nexus/model/my_variant_info_model/Homozygotes.java
  model/src/main/java/org/cbioportal/genome_nexus/model/my_variant_info_model/Mutdb.java
  model/src/main/java/org/cbioportal/genome_nexus/model/my_variant_info_model/MyVariantInfo.java
  model/src/main/java/org/cbioportal/genome_nexus/model/my_variant_info_model/Rcv.java
  model/src/main/java/org/cbioportal/genome_nexus/model/my_variant_info_model/Snpeff.java
  model/src/main/java/org/cbioportal/genome_nexus/model/my_variant_info_model/Vcf.java
  service/src/main/java/org/cbioportal/genome_nexus/service/cached/CachedMyVariantInfoFetcher.java
Labels: test

#695 Specify Reference Assembly When Calling OncoKB API
  component/src/main/java/org/cbioportal/genome_nexus/component/annotation/OncokbResolver.java
  model/src/main/java/org/cbioportal/genome_nexus/model/Alteration.java
  service/src/main/java/org/cbioportal/genome_nexus/service/internal/OncokbServiceImpl.java
Labels: bug
