Repository genome-nexus/genome-nexus, pull requests merged in 2023-09, with the labels that each got.

#709 Add error message for VEP error on POST requests
  service/src/main/java/org/cbioportal/genome_nexus/service/cached/BaseCachedVariantAnnotationFetcher.java
Labels: enhancement

#710 Support missing end position
  component/src/main/java/org/cbioportal/genome_nexus/component/annotation/NotationConverter.java
  model/src/main/java/org/cbioportal/genome_nexus/model/GenomicLocation.java
Labels: bug

#706 Change my variant info clinvar field name
  model/src/main/java/org/cbioportal/genome_nexus/model/my_variant_info_model/MyVariantInfo.java
  model/src/main/java/org/cbioportal/genome_nexus/model/my_variant_info_model/MyVariantInfoClinVar.java
  service/src/main/java/org/cbioportal/genome_nexus/service/config/ExternalResourceObjectMapper.java
  service/src/main/java/org/cbioportal/genome_nexus/service/mixin/my_variant_info_mixin/MyVariantInfoClinVarMixin.java
  service/src/main/java/org/cbioportal/genome_nexus/service/mixin/my_variant_info_mixin/MyVariantInfoMixin.java
  web/src/main/java/org/cbioportal/genome_nexus/web/config/ApiObjectMapper.java
  web/src/main/java/org/cbioportal/genome_nexus/web/mixin/VariantAnnotationMixin.java
  web/src/main/java/org/cbioportal/genome_nexus/web/mixin/my_variant_info_mixin/MyVariantInfoClinVarMixin.java
  web/src/main/java/org/cbioportal/genome_nexus/web/mixin/my_variant_info_mixin/MyVariantInfoMixin.java
Labels: enhancement

#712 Fix docker build test to use multiarch build
  .github/workflows/test_docker_build.yml
  Dockerfile
Labels: test, dependencies
